version: "3.8"

services:
  stock-mkt.app:
    build:
      context: .
    entrypoint: /app/scripts/init.api.sh
    env_file:
      - .env
    volumes:

      - type: bind
        source: ./stock_mkt
        target: /app/stock_mkt/

      - type: bind
        source: ./tests
        target: /app/tests/

    ports:
      - "8080:8000"  # Main port
      - "5555:5555"  # Debug port
    networks:
      - stock-mkt-ntw

  mongo.db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - stock-mkt-ntw

  cache.db:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - stock-mkt-ntw

volumes:
  stock-mkt-data:
  mongo-data:

networks:
  # The presence of these objects is sufficient to define them
  stock-mkt-ntw: {}
